/**
 * Sloane's Tool Layer
 * 
 * Each tool represents a capability Sloane can use.
 * Tools are designed to be swappable — mock implementations now,
 * real API integrations later.
 */

export interface ToolResult {
  success: boolean;
  data?: unknown;
  message: string;
}

// ============================================
// Calendar Tool
// ============================================
export interface CalendarEvent {
  id: string;
  title: string;
  start: string;
  end: string;
  attendees?: string[];
  location?: string;
  description?: string;
}

export async function getCalendarEvents(
  _clientId: string,
  _date?: string
): Promise<ToolResult> {
  // TODO: Wire to Google Calendar API
  const mockEvents: CalendarEvent[] = [
    {
      id: "evt-1",
      title: "Team Standup",
      start: "2026-03-06T09:00:00",
      end: "2026-03-06T09:30:00",
      attendees: ["alex@acme.com", "sarah@acme.com"],
    },
    {
      id: "evt-2",
      title: "Client Call — Vertex Partners",
      start: "2026-03-06T14:00:00",
      end: "2026-03-06T15:00:00",
      attendees: ["mike@vertex.com"],
      location: "Zoom",
    },
  ];
  return { success: true, data: mockEvents, message: "Retrieved calendar events" };
}

export async function createCalendarEvent(
  _clientId: string,
  _event: Partial<CalendarEvent>
): Promise<ToolResult> {
  // TODO: Wire to Google Calendar API
  return {
    success: true,
    data: { id: `evt-${Date.now()}`, status: "pending_approval" },
    message: "Calendar event created (pending approval)",
  };
}

// ============================================
// Email Tool
// ============================================
export interface EmailDraft {
  id: string;
  to: string;
  subject: string;
  body: string;
  status: "draft" | "pending_approval" | "sent";
}

export async function draftEmail(
  _clientId: string,
  _to: string,
  _subject: string,
  _body: string
): Promise<ToolResult> {
  // TODO: Wire to Gmail API
  const draft: EmailDraft = {
    id: `email-${Date.now()}`,
    to: _to,
    subject: _subject,
    body: _body,
    status: "draft",
  };
  return { success: true, data: draft, message: "Email drafted" };
}

export async function sendEmail(
  _clientId: string,
  _emailId: string
): Promise<ToolResult> {
  // TODO: Wire to Gmail API — requires approval gate
  return {
    success: true,
    data: { id: _emailId, status: "sent" },
    message: "Email sent",
  };
}

// ============================================
// Research Tool
// ============================================
export interface ResearchResult {
  query: string;
  summary: string;
  sources: { title: string; url: string }[];
}

export async function doResearch(
  _query: string
): Promise<ToolResult> {
  // TODO: Wire to web search API + LLM summarization
  const result: ResearchResult = {
    query: _query,
    summary: `Research summary for "${_query}" — this will be generated by the LLM with real web search results in production.`,
    sources: [
      { title: "Source 1", url: "https://example.com/1" },
      { title: "Source 2", url: "https://example.com/2" },
    ],
  };
  return { success: true, data: result, message: "Research complete" };
}

// ============================================
// Task Tool
// ============================================
export interface Task {
  id: string;
  title: string;
  status: "pending" | "in_progress" | "done";
  dueDate?: string;
  createdAt: string;
}

// In-memory store for MVP — Supabase in production
const taskStore: Map<string, Task[]> = new Map();

export async function createTask(
  clientId: string,
  title: string,
  dueDate?: string
): Promise<ToolResult> {
  const tasks = taskStore.get(clientId) || [];
  const task: Task = {
    id: `task-${Date.now()}`,
    title,
    status: "pending",
    dueDate,
    createdAt: new Date().toISOString(),
  };
  tasks.push(task);
  taskStore.set(clientId, tasks);
  return { success: true, data: task, message: "Task created" };
}

export async function listTasks(
  clientId: string
): Promise<ToolResult> {
  const tasks = taskStore.get(clientId) || [];
  return { success: true, data: tasks, message: `Found ${tasks.length} tasks` };
}

// ============================================
// Activity Logger
// ============================================
export interface ActivityEntry {
  id: string;
  clientId: string;
  action: string;
  intent: string;
  timestamp: string;
  requiresApproval: boolean;
  status: "completed" | "pending_approval" | "approved" | "rejected";
}

const activityLog: ActivityEntry[] = [];

export function logActivity(entry: Omit<ActivityEntry, "id" | "timestamp">): ActivityEntry {
  const full: ActivityEntry = {
    ...entry,
    id: `act-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    timestamp: new Date().toISOString(),
  };
  activityLog.push(full);
  return full;
}

export function getActivities(clientId?: string, limit = 50): ActivityEntry[] {
  const filtered = clientId
    ? activityLog.filter((a) => a.clientId === clientId)
    : activityLog;
  return filtered.slice(-limit).reverse();
}
